# Generated by Django 4.2.18 on 2025-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                ("style_personality_accuracy", models.IntegerField()),
                ("clothing_suggestions_accuracy", models.IntegerField()),
                ("style_personality_thoughts", models.TextField(blank=True, null=True)),
                ("body_type_accuracy", models.IntegerField()),
                ("body_type_suggestions_accuracy", models.IntegerField()),
                ("body_type_thoughts", models.TextField(blank=True, null=True)),
                ("outfit_challenge", models.CharField(max_length=255)),
                ("quiz_improvements", models.JSONField(blank=True, null=True)),
                ("quiz_improvements_other", models.TextField(blank=True, null=True)),
                ("styling_service", models.CharField(max_length=255)),
                ("styling_service_price", models.CharField(max_length=255)),
                ("final_thoughts", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("responses", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
